//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: sss_token
// ----------------------------------------------------------------------------
pub mod sss_token {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_token
    pub fn program_id() -> Pubkey {
        pubkey!("Fjv9YM4CUWFgQZQzLyD42JojLcDJ2yPG7WDEaR7U14n1")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAuthority
    // ....................................................................

    /// Main instruction struct for AcceptAuthority
    pub struct AcceptAuthorityInstruction {
        pub accounts: AcceptAuthorityInstructionAccountMetas,
        pub data: AcceptAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAuthorityInstructionAccountMetas {
        pub new_authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for AcceptAuthority instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAuthorityInstructionAccounts {
        pub new_authority: Pubkey,

        pub config: Pubkey,
    }

    impl AcceptAuthorityInstructionAccounts {
        pub fn new(new_authority: Pubkey, config: Pubkey) -> Self {
            Self {
                new_authority,

                config,
            }
        }
    }

    /// Instruction data for AcceptAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAuthorityInstructionData {}

    impl AcceptAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAuthorityInstruction
    impl AcceptAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [107u8, 86u8, 198u8, 91u8, 33u8, 12u8, 107u8, 160u8]
        }

        pub fn data(data: AcceptAuthorityInstructionData) -> Self {
            Self {
                accounts: AcceptAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAuthorityInstructionAccounts) -> Self {
            self.accounts.new_authority = AccountMeta::new_readonly(accounts.new_authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.new_authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            config: Pubkey,

            role_assignment: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                config,

                role_assignment,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub address: Pubkey,

        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(address: Pubkey, reason: String) -> Self {
            Self { address, reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Burn
    // ....................................................................

    /// Main instruction struct for Burn
    pub struct BurnInstruction {
        pub accounts: BurnInstructionAccountMetas,
        pub data: BurnInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Burn instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnInstructionAccountMetas {
        pub burner: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,

        pub mint: AccountMeta,

        pub burner_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Burn instruction
    #[derive(Debug, Clone)]
    pub struct BurnInstructionAccounts {
        pub burner: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,

        pub mint: Pubkey,

        pub burner_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl BurnInstructionAccounts {
        pub fn new(
            burner: Pubkey,

            config: Pubkey,

            role_assignment: Pubkey,

            mint: Pubkey,

            burner_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                burner,

                config,

                role_assignment,

                mint,

                burner_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Burn
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnInstructionData {
        pub amount: u64,
    }

    impl BurnInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnInstruction
    impl BurnInstruction {
        fn discriminator() -> [u8; 8] {
            [116u8, 110u8, 29u8, 56u8, 107u8, 219u8, 42u8, 93u8]
        }

        pub fn data(data: BurnInstructionData) -> Self {
            Self {
                accounts: BurnInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnInstructionAccounts) -> Self {
            self.accounts.burner = AccountMeta::new(accounts.burner, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.burner_token_account =
                AccountMeta::new(accounts.burner_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.burner.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.burner_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                mint,

                token_account,

                token_program,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_program: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_program,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub params: InitializeParams,
    }

    impl InitializeInstructionData {
        pub fn new(params: InitializeParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Mint
    // ....................................................................

    /// Main instruction struct for Mint
    pub struct MintInstruction {
        pub accounts: MintInstructionAccountMetas,
        pub data: MintInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Mint instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintInstructionAccountMetas {
        pub minter: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,

        pub minter_config: AccountMeta,

        pub mint: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Mint instruction
    #[derive(Debug, Clone)]
    pub struct MintInstructionAccounts {
        pub minter: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,

        pub minter_config: Pubkey,

        pub mint: Pubkey,

        pub recipient_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl MintInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            config: Pubkey,

            role_assignment: Pubkey,

            minter_config: Pubkey,

            mint: Pubkey,

            recipient_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                minter,

                config,

                role_assignment,

                minter_config,

                mint,

                recipient_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Mint
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintInstructionData {
        pub amount: u64,
    }

    impl MintInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintInstruction
    impl MintInstruction {
        fn discriminator() -> [u8; 8] {
            [51u8, 57u8, 225u8, 47u8, 182u8, 146u8, 137u8, 166u8]
        }

        pub fn data(data: MintInstructionData) -> Self {
            Self {
                accounts: MintInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new(accounts.minter, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self.accounts.minter_config = AccountMeta::new(accounts.minter_config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.push(self.accounts.minter_config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey, role_assignment: Pubkey) -> Self {
            Self {
                pauser,

                config,

                role_assignment,
            }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProposeAuthority
    // ....................................................................

    /// Main instruction struct for ProposeAuthority
    pub struct ProposeAuthorityInstruction {
        pub accounts: ProposeAuthorityInstructionAccountMetas,
        pub data: ProposeAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProposeAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProposeAuthorityInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for ProposeAuthority instruction
    #[derive(Debug, Clone)]
    pub struct ProposeAuthorityInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl ProposeAuthorityInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for ProposeAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProposeAuthorityInstructionData {
        pub new_authority: Pubkey,
    }

    impl ProposeAuthorityInstructionData {
        pub fn new(new_authority: Pubkey) -> Self {
            Self { new_authority }
        }
    }

    /// Implementation for ProposeAuthorityInstruction
    impl ProposeAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [20u8, 148u8, 236u8, 198u8, 76u8, 119u8, 99u8, 142u8]
        }

        pub fn data(data: ProposeAuthorityInstructionData) -> Self {
            Self {
                accounts: ProposeAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProposeAuthorityInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,

        pub blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            config: Pubkey,

            role_assignment: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                config,

                role_assignment,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {
        pub address: Pubkey,
    }

    impl RemoveFromBlacklistInstructionData {
        pub fn new(address: Pubkey) -> Self {
            Self { address }
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new_readonly(accounts.blacklister, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub seizer: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,

        pub mint: AccountMeta,

        pub source_token_account: AccountMeta,

        pub treasury_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub seizer: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,

        pub mint: Pubkey,

        pub source_token_account: Pubkey,

        pub treasury_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            seizer: Pubkey,

            config: Pubkey,

            role_assignment: Pubkey,

            mint: Pubkey,

            source_token_account: Pubkey,

            treasury_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                seizer,

                config,

                role_assignment,

                mint,

                source_token_account,

                treasury_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.seizer = AccountMeta::new_readonly(accounts.seizer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.source_token_account =
                AccountMeta::new(accounts.source_token_account, false);

            self.accounts.treasury_token_account =
                AccountMeta::new(accounts.treasury_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.seizer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.source_token_account.clone());

            metas.push(self.accounts.treasury_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                mint,

                token_account,

                token_program,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey, role_assignment: Pubkey) -> Self {
            Self {
                pauser,

                config,

                role_assignment,
            }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_assignment =
                AccountMeta::new_readonly(accounts.role_assignment, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinter
    // ....................................................................

    /// Main instruction struct for UpdateMinter
    pub struct UpdateMinterInstruction {
        pub accounts: UpdateMinterInstructionAccountMetas,
        pub data: UpdateMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub minter_config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateMinter instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub minter_config: Pubkey,
    }

    impl UpdateMinterInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, minter_config: Pubkey) -> Self {
            Self {
                authority,

                config,

                minter_config,
            }
        }
    }

    /// Instruction data for UpdateMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterInstructionData {
        pub minter_address: Pubkey,

        pub action: MinterAction,
    }

    impl UpdateMinterInstructionData {
        pub fn new(minter_address: Pubkey, action: MinterAction) -> Self {
            Self {
                minter_address,

                action,
            }
        }
    }

    /// Implementation for UpdateMinterInstruction
    impl UpdateMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [164u8, 129u8, 164u8, 88u8, 75u8, 29u8, 91u8, 38u8]
        }

        pub fn data(data: UpdateMinterInstructionData) -> Self {
            Self {
                accounts: UpdateMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_config = AccountMeta::new(accounts.minter_config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoles
    // ....................................................................

    /// Main instruction struct for UpdateRoles
    pub struct UpdateRolesInstruction {
        pub accounts: UpdateRolesInstructionAccountMetas,
        pub data: UpdateRolesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoles instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRolesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub role_assignment: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateRoles instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRolesInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub role_assignment: Pubkey,
    }

    impl UpdateRolesInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, role_assignment: Pubkey) -> Self {
            Self {
                authority,

                config,

                role_assignment,
            }
        }
    }

    /// Instruction data for UpdateRoles
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRolesInstructionData {
        pub address: Pubkey,

        pub role: RoleType,

        pub action: RoleAction,
    }

    impl UpdateRolesInstructionData {
        pub fn new(address: Pubkey, role: RoleType, action: RoleAction) -> Self {
            Self {
                address,

                role,

                action,
            }
        }
    }

    /// Implementation for UpdateRolesInstruction
    impl UpdateRolesInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 152u8, 205u8, 233u8, 177u8, 123u8, 219u8, 125u8]
        }

        pub fn data(data: UpdateRolesInstructionData) -> Self {
            Self {
                accounts: UpdateRolesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRolesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_assignment = AccountMeta::new(accounts.role_assignment, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_assignment.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: transfer_hook
// ----------------------------------------------------------------------------
pub mod transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("7z98ECJDGgRTZgnkX4iY8F6yqLBkiFKXJR2p51jrvUaj")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: InitializeExtraAccountMetaList
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetaList
    pub struct InitializeExtraAccountMetaListInstruction {
        pub accounts: InitializeExtraAccountMetaListInstructionAccountMetas,
        pub data: InitializeExtraAccountMetaListInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetaListInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            extra_account_meta_list: Pubkey,

            mint: Pubkey,

            config: Pubkey,
        ) -> Self {
            Self {
                payer,

                extra_account_meta_list,

                mint,

                config,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetaList
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionData {
        pub sss_token_program_id: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionData {
        pub fn new(sss_token_program_id: Pubkey) -> Self {
            Self {
                sss_token_program_id,
            }
        }
    }

    /// Implementation for InitializeExtraAccountMetaListInstruction
    impl InitializeExtraAccountMetaListInstruction {
        fn discriminator() -> [u8; 8] {
            [92u8, 197u8, 174u8, 197u8, 41u8, 124u8, 19u8, 3u8]
        }

        pub fn data(data: InitializeExtraAccountMetaListInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetaListInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetaListInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source_token: AccountMeta,

        pub mint: AccountMeta,

        pub destination_token: AccountMeta,

        pub owner: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub sss_token_program: AccountMeta,

        pub config: AccountMeta,

        pub source_blacklist_entry: AccountMeta,

        pub dest_blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source_token: Pubkey,

        pub mint: Pubkey,

        pub destination_token: Pubkey,

        pub owner: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub sss_token_program: Pubkey,

        pub config: Pubkey,

        pub source_blacklist_entry: Pubkey,

        pub dest_blacklist_entry: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source_token: Pubkey,

            mint: Pubkey,

            destination_token: Pubkey,

            owner: Pubkey,

            extra_account_meta_list: Pubkey,

            sss_token_program: Pubkey,

            config: Pubkey,

            source_blacklist_entry: Pubkey,

            dest_blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                source_token,

                mint,

                destination_token,

                owner,

                extra_account_meta_list,

                sss_token_program,

                config,

                source_blacklist_entry,

                dest_blacklist_entry,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub _amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(_amount: u64) -> Self {
            Self { _amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 57u8, 220u8, 152u8, 126u8, 125u8, 97u8, 168u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source_token = AccountMeta::new_readonly(accounts.source_token, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination_token =
                AccountMeta::new_readonly(accounts.destination_token, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.sss_token_program =
                AccountMeta::new_readonly(accounts.sss_token_program, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.source_blacklist_entry =
                AccountMeta::new_readonly(accounts.source_blacklist_entry, false);

            self.accounts.dest_blacklist_entry =
                AccountMeta::new_readonly(accounts.dest_blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source_token.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination_token.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.sss_token_program.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.source_blacklist_entry.clone());

            metas.push(self.accounts.dest_blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AuthorityAcceptedEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityAcceptedEvent {
    pub old_authority: Pubkey,

    pub new_authority: Pubkey,

    pub timestamp: i64,
}

impl AuthorityAcceptedEvent {
    pub fn new(old_authority: Pubkey, new_authority: Pubkey, timestamp: i64) -> Self {
        Self {
            old_authority,

            new_authority,

            timestamp,
        }
    }
}

/// Custom struct: AuthorityProposedEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityProposedEvent {
    pub authority: Pubkey,

    pub proposed: Pubkey,

    pub timestamp: i64,
}

impl AuthorityProposedEvent {
    pub fn new(authority: Pubkey, proposed: Pubkey, timestamp: i64) -> Self {
        Self {
            authority,

            proposed,

            timestamp,
        }
    }
}

/// Custom struct: BlacklistAddEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistAddEvent {
    pub authority: Pubkey,

    pub address: Pubkey,

    pub reason: String,

    pub timestamp: i64,
}

impl BlacklistAddEvent {
    pub fn new(authority: Pubkey, address: Pubkey, reason: String, timestamp: i64) -> Self {
        Self {
            authority,

            address,

            reason,

            timestamp,
        }
    }
}

/// Custom struct: BlacklistEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistEntry {
    pub config: Pubkey,

    pub address: Pubkey,

    pub reason: String,

    pub blacklisted_at: i64,

    pub blacklisted_by: Pubkey,

    pub active: bool,

    pub bump: u8,

    pub _reserved: [u8; 64],
}

impl BlacklistEntry {
    pub fn new(
        config: Pubkey,

        address: Pubkey,

        reason: String,

        blacklisted_at: i64,

        blacklisted_by: Pubkey,

        active: bool,

        bump: u8,

        _reserved: [u8; 64],
    ) -> Self {
        Self {
            config,

            address,

            reason,

            blacklisted_at,

            blacklisted_by,

            active,

            bump,

            _reserved,
        }
    }
}

/// Custom struct: BlacklistRemoveEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistRemoveEvent {
    pub authority: Pubkey,

    pub address: Pubkey,

    pub timestamp: i64,
}

impl BlacklistRemoveEvent {
    pub fn new(authority: Pubkey, address: Pubkey, timestamp: i64) -> Self {
        Self {
            authority,

            address,

            timestamp,
        }
    }
}

/// Custom struct: BurnEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BurnEvent {
    pub authority: Pubkey,

    pub burner: Pubkey,

    pub amount: u64,

    pub timestamp: i64,
}

impl BurnEvent {
    pub fn new(authority: Pubkey, burner: Pubkey, amount: u64, timestamp: i64) -> Self {
        Self {
            authority,

            burner,

            amount,

            timestamp,
        }
    }
}

/// Custom struct: FreezeEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FreezeEvent {
    pub authority: Pubkey,

    pub account: Pubkey,

    pub timestamp: i64,
}

impl FreezeEvent {
    pub fn new(authority: Pubkey, account: Pubkey, timestamp: i64) -> Self {
        Self {
            authority,

            account,

            timestamp,
        }
    }
}

/// Custom struct: InitializeEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeEvent {
    pub authority: Pubkey,

    pub mint: Pubkey,

    pub treasury: Pubkey,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub timestamp: i64,
}

impl InitializeEvent {
    pub fn new(
        authority: Pubkey,

        mint: Pubkey,

        treasury: Pubkey,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        timestamp: i64,
    ) -> Self {
        Self {
            authority,

            mint,

            treasury,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            timestamp,
        }
    }
}

/// Custom struct: InitializeParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeParams {
    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub transfer_hook_program_id: Option<Pubkey>,

    pub treasury: Pubkey,
}

impl InitializeParams {
    pub fn new(
        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        transfer_hook_program_id: Option<Pubkey>,

        treasury: Pubkey,
    ) -> Self {
        Self {
            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            transfer_hook_program_id,

            treasury,
        }
    }
}

/// Custom struct: MintEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MintEvent {
    pub authority: Pubkey,

    pub minter: Pubkey,

    pub recipient: Pubkey,

    pub amount: u64,

    pub remaining_quota: u64,

    pub timestamp: i64,
}

impl MintEvent {
    pub fn new(
        authority: Pubkey,

        minter: Pubkey,

        recipient: Pubkey,

        amount: u64,

        remaining_quota: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            authority,

            minter,

            recipient,

            amount,

            remaining_quota,

            timestamp,
        }
    }
}

/// Custom enum: MinterAction
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum MinterAction {
    Add { quota: u64 },

    UpdateQuota { new_quota: u64 },

    Remove,
}

/// Custom struct: MinterConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterConfig {
    pub config: Pubkey,

    pub minter: Pubkey,

    pub quota_total: u64,

    pub quota_remaining: u64,

    pub bump: u8,

    pub _reserved: [u8; 64],
}

impl MinterConfig {
    pub fn new(
        config: Pubkey,

        minter: Pubkey,

        quota_total: u64,

        quota_remaining: u64,

        bump: u8,

        _reserved: [u8; 64],
    ) -> Self {
        Self {
            config,

            minter,

            quota_total,

            quota_remaining,

            bump,

            _reserved,
        }
    }
}

/// Custom struct: MinterUpdatedEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterUpdatedEvent {
    pub authority: Pubkey,

    pub minter: Pubkey,

    pub quota_total: u64,

    pub quota_remaining: u64,

    pub action: String,

    pub timestamp: i64,
}

impl MinterUpdatedEvent {
    pub fn new(
        authority: Pubkey,

        minter: Pubkey,

        quota_total: u64,

        quota_remaining: u64,

        action: String,

        timestamp: i64,
    ) -> Self {
        Self {
            authority,

            minter,

            quota_total,

            quota_remaining,

            action,

            timestamp,
        }
    }
}

/// Custom struct: PauseEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PauseEvent {
    pub authority: Pubkey,

    pub timestamp: i64,
}

impl PauseEvent {
    pub fn new(authority: Pubkey, timestamp: i64) -> Self {
        Self {
            authority,

            timestamp,
        }
    }
}

/// Custom enum: RoleAction
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum RoleAction {
    Assign,

    Revoke,
}

/// Custom struct: RoleAssignment
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleAssignment {
    pub config: Pubkey,

    pub role_type: u8,

    pub address: Pubkey,

    pub assigned_by: Pubkey,

    pub assigned_at: i64,

    pub bump: u8,

    pub _reserved: [u8; 64],
}

impl RoleAssignment {
    pub fn new(
        config: Pubkey,

        role_type: u8,

        address: Pubkey,

        assigned_by: Pubkey,

        assigned_at: i64,

        bump: u8,

        _reserved: [u8; 64],
    ) -> Self {
        Self {
            config,

            role_type,

            address,

            assigned_by,

            assigned_at,

            bump,

            _reserved,
        }
    }
}

/// Custom enum: RoleType
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum RoleType {
    Minter,

    Burner,

    Pauser,

    Blacklister,

    Seizer,
}

/// Custom struct: RoleUpdatedEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleUpdatedEvent {
    pub authority: Pubkey,

    pub address: Pubkey,

    pub role: u8,

    pub action: String,

    pub timestamp: i64,
}

impl RoleUpdatedEvent {
    pub fn new(
        authority: Pubkey,

        address: Pubkey,

        role: u8,

        action: String,

        timestamp: i64,
    ) -> Self {
        Self {
            authority,

            address,

            role,

            action,

            timestamp,
        }
    }
}

/// Custom struct: SeizeEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SeizeEvent {
    pub authority: Pubkey,

    pub source: Pubkey,

    pub treasury: Pubkey,

    pub amount: u64,

    pub timestamp: i64,
}

impl SeizeEvent {
    pub fn new(
        authority: Pubkey,

        source: Pubkey,

        treasury: Pubkey,

        amount: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            authority,

            source,

            treasury,

            amount,

            timestamp,
        }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub authority: Pubkey,

    pub pending_authority: Option<Pubkey>,

    pub mint: Pubkey,

    pub treasury: Pubkey,

    pub decimals: u8,

    pub paused: bool,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub transfer_hook_program: Option<Pubkey>,

    pub total_minted: u64,

    pub total_burned: u64,

    pub bump: u8,

    pub _reserved: [u8; 64],
}

impl StablecoinConfig {
    pub fn new(
        authority: Pubkey,

        pending_authority: Option<Pubkey>,

        mint: Pubkey,

        treasury: Pubkey,

        decimals: u8,

        paused: bool,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        transfer_hook_program: Option<Pubkey>,

        total_minted: u64,

        total_burned: u64,

        bump: u8,

        _reserved: [u8; 64],
    ) -> Self {
        Self {
            authority,

            pending_authority,

            mint,

            treasury,

            decimals,

            paused,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            transfer_hook_program,

            total_minted,

            total_burned,

            bump,

            _reserved,
        }
    }
}

/// Custom struct: ThawEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ThawEvent {
    pub authority: Pubkey,

    pub account: Pubkey,

    pub timestamp: i64,
}

impl ThawEvent {
    pub fn new(authority: Pubkey, account: Pubkey, timestamp: i64) -> Self {
        Self {
            authority,

            account,

            timestamp,
        }
    }
}

/// Custom struct: UnpauseEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UnpauseEvent {
    pub authority: Pubkey,

    pub timestamp: i64,
}

impl UnpauseEvent {
    pub fn new(authority: Pubkey, timestamp: i64) -> Self {
        Self {
            authority,

            timestamp,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
